### ISSUE TITLE
Plug-in XML not well formed error

### ISSUE THREAD

**Issue by staypufd** [zjhmale/intellij-clojure-pretty-symbol#1]
When using Cursive Plugin in IntelliJ 15.0.5 Build #IC-143.2287 I get a error about the plugin xml not being well formed while trying to add the plugin to the Managed Repositories of IntelliJ plugins.

**Comment by swr1bm86** [comment]
thx!, i developed it use Intellij 14.1.6 Build #IC-141.3056 and works fine with Idea 13 and 14, i will fix it as soon as possible :)

**Comment by swr1bm86** [comment]
hey @staypufd , i think this plugin works well with Intellij 15 ecosystem, seems like you got error when installing Cursive plugin? best way to install it is just open the plugin window and click `Browse Repositories…` button and simply search `Cursive` there, there is no need to add plugin to the `Managed Repositories` for now, that's a deprecated way.

**Comment by staypufd** [comment]
Cool thanks

**Comment by swr1bm86** [comment]
you're welcome :)
