### ISSUE TITLE
table of pretty symbols

### ISSUE THREAD

**Issue by shaunlebron** [zjhmale/intellij-clojure-pretty-symbol#13]
in the readme, would be nice to see a two-columned table showing what this plugin replaces

| original | new |
| --- | --- |
| `defn` | ... |
| `fn` | ... |
| `let` | ... |
| etc | ... |

**Comment by swr1bm86** [comment]
@shaunlebron ok i will add it later, thx for reporting :)

**Comment by swr1bm86** [comment]
@shaunlebron now we got the table 🎉 .

**Comment by shaunlebron** [comment]
sweet 👍
