### ISSUE TITLE
Capture highlighted var/symbol from Cursive for extension

### ISSUE THREAD

**Issue by theronic** [zjhmale/intellij-clojure-pretty-symbol#16]
I want to sequence some music and store the result in the highlighted atom symbol, i.e. `#(reset! the-highlighted-symbol {:some-notes [5 6 7 ]})`.

Is there a way to interact with Cursive from the REPL to enumerate or detect clicking on a symbol in the text editor so that I can capture that var and trigger an input dialog?

**Comment by theronic** [comment]
sorry wrong project :)

**Comment by swr1bm86** [comment]
No worries 😄
