### ISSUE TITLE
Incompatible with IntelliJ 2019.3

### ISSUE THREAD

**Issue by Sardtok** [zjhmale/intellij-clojure-pretty-symbol#18]
![clj-pretty-2019 3](https://user-images.githubusercontent.com/613667/69862031-e042ec80-1299-11ea-9616-c8081497cc33.png)

When using clojure pretty symbol with 2019.3, I only see ellipses for all the symbols. The above screenshot is a function with a let and a lambda. As you can see, the symbols are not showing correctly. Worked fine in 2019.2.

**Comment by pablo-develop** [comment]
same here

**Comment by neuromantik33** [comment]
+1

**Comment by luishendrix92** [comment]
Same, ... appears

**Comment by ghost** [comment]
+1

**Comment by neuromantik33** [comment]
Fixed with the latest version of Intellij 2020.1!! :)
