### ISSUE TITLE
def is replaced by symbol on some lines, even when that option is turned off

### ISSUE THREAD

**Issue by Engelberg** [zjhmale/intellij-clojure-pretty-symbol#2]
I have disabled def in the settings for the plugin, but some lines (not all) still replace def with the symbol.  I have no idea why it does it for some lines but not others.

**Comment by swr1bm86** [comment]
i will fix it out. thx!
btw, can you put the code snippets here which comes out unexpected behavior? @Engelberg

**Comment by swr1bm86** [comment]
there is no need to put code snippets here. i just fixed this issue.

i think after disabled def in the settings.

something like

``` clojure
(def a 1)
```

will still replace def with the symbol

and something like

``` clojure
(def a (+ 1 2))
```

will not replace.

i will upgrade this plugin to use kotlin and gradle later, so this bug fix will not upload to Jetbrain Plugin system immediately, just wait for most two days.

thx again :)

**Comment by Engelberg** [comment]
Thanks.  P.S.  I'd be interested in symbols for <= and >=.

**Comment by swr1bm86** [comment]
:+1: that's also exactly what i want, Math rocks! :)

**Comment by swr1bm86** [comment]
@Engelberg i just upload a new release. 
- fix the def symbol settings bug.
- support `>=` `<=` symbol and the bind symbol `>>=` will not be replaced.

![2016-03-22 8 38 39](https://cloud.githubusercontent.com/assets/6234553/13952155/d14ac806-f06f-11e5-8f8d-3faae0b47eba.png)

you can update the plugin now, Cheers!
