### ISSUE TITLE
make show up pretty symbol in string literal configurable

### ISSUE THREAD

**Issue by zxs1215** [zjhmale/intellij-clojure-pretty-symbol#5]
What I typed：  ", and "
What Intellij shows: ", Λ "
I think it's a bug
It won't change when 'and' is in string。

**Comment by swr1bm86** [comment]
why do you think it's a bug? i intent to show it in string literals, maybe i will add a settings panel to make this optional. thx for reporting, btw.

**Comment by zxs1215** [comment]
cause i want it changes when it's not in string,
and show original characters when is in string.
maybe add an option like "also in string" under "pretty and" is cool.

**Comment by swr1bm86** [comment]
it's just not only happens in `and`, so the option will toggle all the conceals :)

**Comment by n2o** [comment]
i'd also prefer if I can choose wether my strings are replaced or not. I find it kind of disturbing when reading a string and some characters are substituted, like the not:

![bildschirmfoto von 2016-03-30 14-19-37](https://cloud.githubusercontent.com/assets/1507474/14141947/cb31a462-f682-11e5-81c8-7615bdff610c.png)

Great extension, although I just installed it to get my lambda symbol when typing `(fn ...)` as I know it from Emacs and do not use most of your symbols ;-)

**Comment by swr1bm86** [comment]
ok, i will make it optinal soon :)

**Comment by jimpil** [comment]
The same happens with 'or'...I also don't think this should happen in literal strings, but at least if it's made configurable, and potentially disabled by default, everyone will be happy :).

Thanks for doing this work BTW ...

**Comment by swr1bm86** [comment]
hi all @zxs1215 @n2o @jimpil this plugin has bumped up to version 1.5 and now we got a settings checkbox to toggle pretty symbols showing up in string literals, and it is default to turn off as expected.

![image](https://cloud.githubusercontent.com/assets/6234553/14224922/e1781124-f8e0-11e5-8b79-411b2f67aee0.png)

Cheers! :tada:
