### ISSUE TITLE
issue with `not-XXX` expressions

### ISSUE THREAD

**Issue by jimpil** [zjhmale/intellij-clojure-pretty-symbol#6]
The rules for `not` apply to `not-empty`, `not-any?`, `not-every?` etc etc. As a result, any expression starting with `not` looks very weird.

**Comment by swr1bm86** [comment]
ok i will fix that soon, thx for reporting :)

**Comment by swr1bm86** [comment]
hey @jimpil this plugin has updated to v1.5 and this issue is fixed up.

![image](https://cloud.githubusercontent.com/assets/6234553/14224930/48b0af86-f8e1-11e5-9331-632173931f94.png)

Cheers! :tada:
