### ISSUE TITLE
"Caret row" and Cursive colors not being honored

### ISSUE THREAD

**Issue by tylerperkins** [zjhmale/intellij-clojure-pretty-symbol#8]
Thanks for your awesome work!

I use a white background for the current row, but a darker color generally. The pretty symbols work great, but they use the general text colors, even when the caret is in the same row as the symbol. The background of the pretty symbol should be the same as the text it is replacing, whether it's in the current row or not. See image below.

Possibly related: The Cursive highlighting for def, defn, etc. also are not being honored. Again, the colors of the pretty symbol should be the same as the text it is replacing.

![caret row background](https://cloud.githubusercontent.com/assets/607877/14292593/fa432878-fb25-11e5-99e3-9d9ac04077cf.png)

**Comment by swr1bm86** [comment]
@tylerperkins basicly i think there is two ways to get what you want.

**1** the highlight color of a specific symbol is controlled by the color themes and can not be accessed through this plugin, so i can not find a way to automatically set the color of these pretty symbols, but you can set it manully in `Preferences > Editor > Colors & Fonts > General`

![image](https://cloud.githubusercontent.com/assets/6234553/14307386/2f7d9560-fc01-11e5-8ecf-652e5bc768f3.png)

just set the `Foreground color` for the `Folded text` any color you prefered.

![image](https://cloud.githubusercontent.com/assets/6234553/14307413/60321ac8-fc01-11e5-97b1-7e79620f9faf.png)

**2** another way which i prefered is to use this plugin  https://github.com/zjhmale/intellij-rainbow, it will automatically re-render foreground color for every specific symbol even pretty symbols.

![image](https://cloud.githubusercontent.com/assets/6234553/14307506/079b81f0-fc02-11e5-98f9-066ada22c0fc.png)

but not quite a lot of people like the noisy rainbow colors :joy: 

btw, thx for reporting :)

**Comment by tylerperkins** [comment]
Your solutions don't really solve the main problem, which is the **_background_** of the pretty symbols. By the way, I notice that even without Clojure Pretty Symbol, ordinary collapsed text, "Command -", suffers the same problem. So it's probably just a design flaw in IntelliJ.

However, by employing your first solution and experimenting with different background colors for the caret row, I was able to make the discordant background less noticeable. Thanks!

Is there any way to turn off Clojure Pretty Symbol temporarily without collapsing the code? "Command -" works, but you then see only the first line of the s-expression. I'm thinking this is important if you forget what a symbol means, or you want to show your code to someone who isn't used to the symbols.

**Comment by swr1bm86** [comment]
hm, for now, you have to turn off pretty symbols one by one in the settings panel, i will and a global settings checkbox to toggle them together later.

**Comment by swr1bm86** [comment]
@tylerperkins now you can turn on / off pretty symbols globally when you want to see the under layer text after update this plugin, Cheers :tada: 

![snapshot](https://cloud.githubusercontent.com/assets/6234553/14342238/cf4fb3f6-fcca-11e5-97bf-c5ac8b811206.gif)

**Comment by tylerperkins** [comment]
Great, that was quick! However, I don't see unsetting the "Turn on pretty symbols" flag reflected throughout the file, as shown in your animated GIF. If I turn it on, I **_do_** see pretty symbols everywhere in the file once I edit something. But if I go back to Preferences and turn it **_off_**, I only see the change in the line I'm editing. Closing and reopening the file shows all the pretty symbols just when the flag is set, as expected.

What would be great is if a **_hot key_** could be used to toggle pretty symbols on or off without the need to edit something. Maybe it could apply everywhere, or just in the current selection.

**Comment by swr1bm86** [comment]
hey @tylerperkins i got the same problem with IDEA IC-145.256.33 (IDEA 16 EAP), i just fixed it and you can update this plugin :)
-  for now after you click `apply` button on settings panel, the changes will be applied to the current opening file immediately.

![apply](https://cloud.githubusercontent.com/assets/6234553/14385592/e3713bd4-fdd3-11e5-8263-109c0c981c85.gif)
- and also add an action to turn on / off conceal globally.

![toggle](https://cloud.githubusercontent.com/assets/6234553/14385634/1191a2d8-fdd4-11e5-91d7-117a81ce48ea.gif)
- you can bind a shortcut to this action on the keymap panel.

![keymap](https://cloud.githubusercontent.com/assets/6234553/14385633/1160f4bc-fdd4-11e5-81dd-32194148ac1e.png)

**tested with IDEA 14.1.4, 15.0.2 and 16-EAP**

Cheers :tada:

**Comment by tylerperkins** [comment]
Nice! There are still issues, though. See below. My IntelliJ version is the latest official release for the Mac:

```
IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Creating a keyboard shortcut for "Toggle Clojure Pretty Symbol" is a wonderful improvement, making this plugin very useful. However, it does not work as expected with open files that are **_not_** the current one. Both the toggle action and the Preferences flag do not change the appearance of the other files. Nonetheless, the change in **_mode_** is indeed global. You can see which mode is in force in one of the other files only when you go and edit a line there. Then the current mode is visible only for that line, however. The rest of the file reflects the old mode.

Also, strangely, the order of the tabs of currently open files can change after the toggling action or flipping the Preference flag.

Another opportunity for improvement: It's nice that string literals can be made exempt from pretty-ifying, but **_comments_** really should be exempt as well.

**Comment by swr1bm86** [comment]
> it does not work as expected with open files that are not the current one. 

<del>yeah this is a known issue cause if you refresh multiple opening files, the idea will be stucked for seconds and can not guarantee the order of the file tabs, so currently this action and preference flag can only refresh the current file. to solve this maybe you have to apply the action on each of the files with IDEA 16 (it is fine with IDEA 14 and 15)</del>

 i just find a way, and will fix it tomorrow.

> Also, strangely, the order of the tabs of currently open files can change after the toggling action or flipping the Preference flag.

<del>can you show me a GIF for this issue, i can not imagine the problem.</del>

got it, also only comes out with IDEA 16. :joy: <del>but it is not really a big deal right? it does not matter anything here.</del> will fix it tomorrow :)

> Another opportunity for improvement: It's nice that string literals can be made exempt from pretty-ifying, but comments really should be exempt as well.

great, i will add a checkbox to exempt pretty symbols in comment tomorrow, thx!

**Comment by swr1bm86** [comment]
@tylerperkins i think all the three issues are fixed and we are good here :smile: 

![snapshot](https://cloud.githubusercontent.com/assets/6234553/14402313/5c31bf9a-fe64-11e5-899b-908c5357d85f.gif)

but if you have a lot files opening in your current editor, when you apply toggle action or the Preferences flag, it will stuck for seconds cause it has to refresh eash files.

you can update and check, Cheers :tada:
