### ISSUE TITLE
all regex should include a mandatory space at the end

### ISSUE THREAD

**Issue by jimpil** [zjhmale/intellij-clojure-pretty-symbol#9]
Example:

(partial f :a) => should trigger
(partial-amount :whatever) => should NOT trigger

In general, i think you should make all your regexes trigger only if the token in question appears as standalone. That would mean that a /space is always the last character. Hope that helps :)

**Comment by swr1bm86** [comment]
thx, i will fix it tomorrow.

**Comment by jimpil** [comment]
Without having given this too much thought, i think it would make sense to require a \space before AND after the token in question. So basically you can replace the initial "(" character with a \space. Then this (for example) would work:

`(map partial fn-coll arg-coll)`

**Comment by swr1bm86** [comment]
good point! maybe i should refactor the folding strategy :)
